### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by n0yal** [gabrielzschmitz/dotfiles#1]
First of all i3exit cannot be found . When i press the shutdown nothing happens. 

Can you provide solution? I realy need the solution.
The menu is coming when i enter mod key and 0 or pressing the power button on  the polybar but when i select the option for example poweroff or logout nothing happens.

**Comment by 3301n** [comment]
Also zsh is not working properly there is error coming.

**Comment by gabrielzschmitz** [comment]
Can you run the powermenu script in your terminal and give me a screenshot of the error? So I can help you 😃

> $ sh .config/polybar/scripts/powermenu.sh

**Comment by 3301n** [comment]
How to run the script in terminal where is it located?

**Comment by gabrielzschmitz** [comment]
_.config/polybar/scripts/powermenu.sh_

**Comment by 3301n** [comment]
https://user-images.githubusercontent.com/69240615/129367780-739bf2c1-992c-433a-bd5c-ce88d6695d35.mp4

**Comment by gabrielzschmitz** [comment]
Ok, I've found the error. You need to make your user able to run scripts with sudo privileges without asking for password.

**Comment by 3301n** [comment]
https://user-images.githubusercontent.com/69240615/129367896-eb957c42-bca1-4445-a39c-a8b1e2d04261.mp4

**Comment by n0yal** [comment]
can you see the video?

**Comment by gabrielzschmitz** [comment]
That's how you do it:
Open that file /etc/sudoers (with root)
and uncomment that line and line below:
![Fullscreenshot-10:56:16](https://user-images.githubusercontent.com/58743811/129368614-1bd42321-057e-4293-ae8b-887b16d4cc39.png)
Than you will probably need to reboot your machine, but after that all should work as intended.
`%wheel ALL=(ALL) ALL
%wheel ALL=(ALL) NOPASSWD: ALL`

**Comment by n0yal** [comment]
Sry but iam not on arch. Iam using debian

**Comment by gabrielzschmitz** [comment]
So add that line to your /etc/sudoers.d:
`username  ALL=(ALL) NOPASSWD:ALL`
(being "username" your name on the machine)

**Comment by gabrielzschmitz** [comment]
It worked?

**Comment by n0yal** [comment]
It didnt work anyways. But i love the color scheme very much.

**Comment by gabrielzschmitz** [comment]
Try to follow that [guide](https://linuxize.com/post/how-to-add-user-to-sudoers-in-debian/).

**Comment by n0yal** [comment]
But the script is pointing to i3exit but i could not find such thing ?

powermenu.sh: 43: i3exit: not found
Getting this error also

**Comment by n0yal** [comment]
Also my right alt is not working as mod when i changed the mod to alt key.

I have one more request when i press mod + d iam getting dmenu . Instead i want the script that runs when i click the leftmost icon on the polybar.

/home/kali/.config/zsh/.zshrc:source:18: no such file or directory: /home/kali/.config/zsh/zsh-vi-mode/zsh-vi-mode.plugin.zsh
Getting this error when i open terminal everytime.

**Comment by gabrielzschmitz** [comment]
Open different issues to talk about each problems ok?
Thanks.

**Comment by gabrielzschmitz** [comment]
> But the script is pointing to i3exit but i could not find such thing ?
> 
> powermenu.sh: 43: i3exit: not found
> Getting this error also

Is i3exit installed?

**Comment by gabrielzschmitz** [comment]
> /home/kali/.config/zsh/.zshrc:source:18: no such file or directory: /home/kali/.config/zsh/zsh-vi-mode/zsh-vi-mode.plugin.zsh
> Getting this error when i open terminal everytime.

You need to install [zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode) by jeffreytse
`git clone https://github.com/jeffreytse/zsh-vi-mode.git $HOME/.config/zsh/zsh-vi-mode`
