### ISSUE TITLE
Also my right alt is not working as mod when i changed the mod to alt key.

### ISSUE THREAD

**Issue by n0yal** [gabrielzschmitz/dotfiles#2]
I have one more request when i press mod + d iam getting dmenu . Instead i want the script that runs when i click the leftmost icon on the polybar.

_Originally posted by @3301n in https://github.com/gabrielzschmitz/dotfiles/issues/1#issuecomment-899209640_

**Comment by 3301n** [comment]
I cannot type double quotes all i get is a latin character i think ¨ when i click the double quote twice.

**Comment by gabrielzschmitz** [comment]
You just need to change the launcher script. It is in:
`~/.config/polybar/scripts/launcher.sh`

Remove that:
`- rofi -no-config -no-lazy-grab -show drun -mode run -theme ~/.config/polybar/scripts/rofi/launcher.rasi`
and add that:
`+ dmenu_run -p 'dmenu'`

**Comment by gabrielzschmitz** [comment]
About the alt key, I think I3 just uses the left alt for mod key;
Don't know how to make the right one works as well.
