### ISSUE TITLE
Power off button not working.

### ISSUE THREAD

**Issue by n0yal** [gabrielzschmitz/dotfiles#4]
Getting this error when i run powermenu.sh 

powermenu.sh: 43: i3exit: not found

I cannot find i3exit in my repositories.  How to install it or can you send it?

**Comment by gabrielzschmitz** [comment]
Just change this part of the power menu script (using loginctl isted of i3exit)

    chosen="$(echo -e "$options" | dmenu)"
    case $chosen in
        $lock)
	 	    sh ~/.scripts/zerolock.sh
            ;;
        $suspend)
		    loginctl suspend
            ;;
        $logout)
		    loginctl terminate-session $XDG_SESSION_ID
	    ;;
        $reboot)
		    loginctl reboot
    	    ;;
        $shutdown)
    		    loginctl poweroff
            ;;
    esac
It is in the Debian [repositorys](https://manpages.debian.org/buster/systemd/loginctl.1.en.html)
